apiVersion: v1
kind: Service
metadata:
  name: mamays-api-service
spec:
  selector:
    app: mamays-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mamays-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mamays-api
  template:
    metadata:
      labels:
        app: mamays-api
    spec:
      containers:
        - name: mamays-api
          image: mamays-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://filosotigre_db_user:yh1zPTS2u7j2YHRq@mamayscluster.1ykazme.mongodb.net/mamaysdb?retryWrites=true&w=majority&appName=MamaysCluster"
---
apiVersion: v1
kind: Service
metadata:
  name: mamays-frontend-service
spec:
  selector:
    app: mamays-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mamays-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mamays-frontend
  template:
    metadata:
      labels:
        app: mamays-frontend
    spec:
      containers:
        - name: mamays-frontend
          image: mamays-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
